cache:
  directories:
    - $HOME/.m2

language: java

services:
  - docker

stages:
  - test
  - run

install: skip

jobs:
  include:
    - stage: test
      name: "Testing Application"
      services: postgresql
      before_script:
        - psql -c 'CREATE DATABASE clines_test;' -U postgres
      script:
        - make test

    - stage: run
      name: "Run Application to Production"
      script:
        - make run